### ISSUE TITLE
How do you get the script

### ISSUE THREAD

**Issue by Markiplier666sus** [RegularVynixu/Utilities#15]
I'm trying to find a way to execute it into my executor in Roblox doors

**Comment by Markiplier666sus** [comment]
Please help me

Saya (:

**Comment by crookhd** [comment]
https://github.com/RegularVynixu/Utilities/blob/main/Doors/Entity%20Spawner/V2/Source.lua

**Comment by RegularVynixu** [comment]
Unsure what you mean by "it", if you're referring to the Doors Custom Entity Spawner V2 script, please refer to @crookhd's reply.
