### ISSUE TITLE
how copy code?

### ISSUE THREAD

**Issue by rahhhhh6942** [RegularVynixu/Utilities#20]
?

**Comment by mobileuserissueman** [comment]
go to example, and everything's there, customization and stuff, if you want I could give you an a-60 script and my gui

**Comment by rahhhhh6942** [comment]
the code in example no work

**Comment by rahhhhh6942** [comment]
i hate this script it no work

**Comment by rahhhhh6942** [comment]
> go to example, and everything's there, customization and stuff, if you want I could give you an a-60 script and my gui

the code in example no work

**Comment by mobileuserissueman** [comment]
Eh?

**Comment by mobileuserissueman** [comment]
what executor is u using

**Comment by mobileuserissueman** [comment]
Since for me it worked on delta, also there's a lot of examples actually, which one is u talking about?
