### ISSUE TITLE
can we still use asset id's?

### ISSUE THREAD

**Issue by mobileuserissueman** [RegularVynixu/Utilities#21]
the v1 doesn't work anymore, and v2 don't allow asset id, so pls allow

**Comment by RegularVynixu** [comment]
Entity spawner v2 should allow for Roblox asset ids as well as external assets to be used.

**Comment by mobileuserissueman** [comment]
Thanks, wasn't expecting a reply so soon lol

**Comment by mobileuserissueman** [comment]
thanks vynixu
