### ISSUE TITLE
Cant obtain item

### ISSUE THREAD

**Issue by The-gamerf** [RegularVynixu/Utilities#5]
while using the custom pre run shop I can't obtain the item i made. is it because I'm trying to use the m249?

**Comment by rksabde** [comment]
i think thats right

**Comment by rksabde** [comment]
might have to modify the source but i wouldnt do that

**Comment by RegularVynixu** [comment]
Apologies for the very delayed reply. I'm planning on rewriting this module in the near future if you're still interested.

**Comment by RegularVynixu** [comment]
> while using the custom pre run shop I can't obtain the item i made. is it because I'm trying to use the m249?

This is because the item names "Crucifix", "Skeleton Key" and "M249" are blacklisted. When I initially made this module, the game checked against these names and would trigger the anti cheat. (Unsure if this is still the case.)
